name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build application
      run: npm run build
    - name: Deploy to production
      uses: actions/aws-actions/deploy-to-ecs@v1
      with:
        region: us-west-2
        task-definition: production-task-definition
        service: production-service
        cluster: production-cluster
